# Defaults
spec:
  destination:
    server: https://kubernetes.default.svc

# Service Entries
serviceEntries:
  rds:
    host: ""

# Metrics Server
argocd:
  namespace: ""

# Dependencies
istiod:
  global:
    tracer:
      zipkin:
        address: jaeger-tracing-collector.telemetry:9411
